# Site settings
name: Silver Shark
description: "Silver Shark is a mobile app development agency located in Tallinn, Estonia.<br>Drop us a mail for inquiries"
title: "Silver Shark"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  silver-shark
email: info@silvershark.app


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars0.githubusercontent.com/u/49716709?s=400&u=fe1ffdcb2f2754501c3e65dd6b17c88084d9263a&v=4"


front_img: yes
front_img_path: "imgs/background.jpg"
# front_img_path: "https://external.url/image.jpg"


favicon_img: no
# favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
